// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdgcxqjxsdraabvpaark.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZ2N4cWp4c2RyYWFidnBhYXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNjk0NTUsImV4cCI6MjA3Njg0NTQ1NX0.HNyTU-evpITk30Qg4kCLFA9BfeBN_VsSPN9dvpa3SbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});